services:
  telegrambot:
    image: imkolganov/openvpn-gate-monitor-telegrambot:latest
    pull_policy: always
    container_name: open-vpn-gate-monitor-telegrambot
    restart: always
    networks:
      - tgbot_network
    volumes:
      - tgbot_data:/app/resources
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      TELEGRAMBOT_PORT: ${TELEGRAMBOT_PORT:-443}
      TELEGRAMBOT_BOT_TOKEN: ${TELEGRAMBOT_BOT_TOKEN:-your-token}
      HOST_ADDRESS: ${HOST_ADDRESS:-localhost}
      USE_CERTIFICATE: ${USE_CERTIFICATE:-true}
      AUTO_GENERATE_CERTIFICATE: ${AUTO_GENERATE_CERTIFICATE:-true}
      CERTIFICATE_PFX_PATH: /app/resources/certs/datagatetgbot.pfx
      CERTIFICATE_PEM_PATH: /app/resources/certs/datagatetgbot.pem
      CERTIFICATE_KEY_PATH: /app/resources/certs/datagatetgbot.key
      CERTIFICATE_ACCOUNT_PATH: /app/resources/certs/account.pem
      CHALLENGE_DIR: /app/resources/wwwroot/.well-known/acme-challenge

      # 🔧 Dashboard API config
      DASHBOARDAPI_URL: ${DASHBOARDAPI_URL:-http://backend:5581/api}
      DASHBOARDAPI_CLIENTID: ${DASHBOARDAPI_CLIENTID:-your-client-id}
      DASHBOARDAPI_CLIENTSECRET: ${DASHBOARDAPI_CLIENTSECRET:-your-client-secret}

      # 📊 Elasticsearch config
      ELASTIC_URI: ${ELASTIC_URI:-http://elasticsearch:9200}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME:-elastic}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-your-password}
      ELASTIC_INDEX_FORMAT: ${ELASTIC_INDEX_FORMAT:-DataGateVPNBot-dev-logs-{0:yyyy.MM.dd}}

    ports:
      - "${TELEGRAMBOT_PORT:-443}:${TELEGRAMBOT_PORT:-443}"
      - "${TELEGRAMBOT_PORT_2:-80}:${TELEGRAMBOT_PORT_2:-80}"

volumes:
  tgbot_data:

networks:
  tgbot_network:
    driver: bridge