version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: open-vpn-gate-monitor-backend
    restart: always
    networks:
      - openvpn_network
    volumes:
      - /home/rackot/configs/OpenVPNGateMonitor/appsettings.json:/app/appsettings.json
      - /home/rackot/configs/OpenVPNGateMonitor/appsettings.Development.json:/app/appsettings.Development.json
      - /home/rackot/certs/datagatetgbot.pem:/app/datagatetgbot.pem
      - /home/rackot/certs/datagatetgbot.key:/app/datagatetgbot.key
      - /usr/share/GeoIP/GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
    ports:
      - "5581:5581"
    environment:
      - FRONTEND_URL=http://frontend:5582
      - DOTNET_ENVIRONMENT=Debug

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: open-vpn-gate-monitor-frontend
    restart: always
    networks:
      - openvpn_network
    ports:
      - "5582:5582"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5581

  openvpn:
    build:
      context: ./openvpn
      dockerfile: Dockerfile
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - openvpn_data:/mnt
      - /home/rackot/configs/server.conf:/mnt/server.conf
    ports:
      - "1195:1195/udp"
    restart: unless-stopped

volumes:
  openvpn_data:

networks:
  openvpn_network:
    driver: bridge
