services:
  backend:
    image: imkolganov/openvpn-gate-monitor-backend:latest
    pull_policy: always
    container_name: open-vpn-gate-monitor-backend
    restart: always
    networks:
      - openvpn_network
      - backend_network
    volumes:
      - backend_data:/app/resources
    ports:
      - "5581:5581"
    depends_on:
      - postgres_backend
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://0.0.0.0:5581
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DB_CONNECTION_STRING_DATAGATE: ${DB_CONNECTION_STRING_DATAGATE:-Host=postgres_backend;Port=5432;Database=datagate_backend;Username=backend_user;Password=securepassword_backend}
      DB_DEFAULT_SCHEMA: xgb_dashopnvpn
      DB_MIGRATION_TABLE: __EFMigrationsHistoryDashboardVpn
      JWT_SECRET:
      # 📊 Elasticsearch config
      ELASTIC_URI: ${ELASTIC_URI:-http://elasticsearch:9200}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME:-elastic}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-your-password}
      ELASTIC_INDEX_FORMAT: ${ELASTIC_INDEX_FORMAT:-OpenVPNGateMonitor-dev-logs-{0:yyyy.MM.dd}}

  frontend:
    image: imkolganov/openvpn-gate-monitor-frontend:latest
    pull_policy: always
    container_name: open-vpn-gate-monitor-frontend
    restart: always
    networks:
      - openvpn_network
    ports:
      - "5582:5582"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:5581

  telegrambot:
    image: imkolganov/openvpn-gate-monitor-telegrambot:latest
    pull_policy: always
    container_name: open-vpn-gate-monitor-telegrambot
    restart: always
    networks:
      - backend_network
      - tgbot_network
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      TELEGRAMBOT_PORT: ${TELEGRAMBOT_PORT:-443}
      TELEGRAMBOT_BOT_TOKEN: ${TELEGRAMBOT_BOT_TOKEN:-your-token}
      HOST_ADDRESS: ${HOST_ADDRESS:-localhost}
      USE_CERTIFICATE: ${USE_CERTIFICATE:-true}
      AUTO_GENERATE_CERTIFICATE: ${AUTO_GENERATE_CERTIFICATE:-true}
      CERTIFICATE_PFX_PATH: /app/certificates/datagatetgbot.pfx
      CERTIFICATE_PEM_PATH: /app/certificates/datagatetgbot.pem
      CERTIFICATE_KEY_PATH: /app/certificates/datagatetgbot.key

      # 🔧 Dashboard API config
      DASHBOARDAPI_URL: ${DASHBOARDAPI_URL:-http://backend:5581/api}
      DASHBOARDAPI_CLIENTID: ${DASHBOARDAPI_CLIENTID:-your-client-id}
      DASHBOARDAPI_CLIENTSECRET: ${DASHBOARDAPI_CLIENTSECRET:-your-client-secret}

      # 📊 Elasticsearch config
      ELASTIC_URI: ${ELASTIC_URI:-http://elasticsearch:9200}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME:-elastic}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-your-password}
      ELASTIC_INDEX_FORMAT: ${ELASTIC_INDEX_FORMAT:-DataGateVPNBot-dev-logs-{0:yyyy.MM.dd}}

    ports:
      - "${TELEGRAMBOT_PORT:-443}:${TELEGRAMBOT_PORT:-443}"
      - "${TELEGRAMBOT_PORT_2:-80}:${TELEGRAMBOT_PORT_2:-80}"

  openvpn_udp:
    image: imkolganov/openvpn-gate-monitor-openvpn:latest
    pull_policy: always
    container_name: openvpn_udp
    restart: unless-stopped
    networks:
      - backend_network
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - openvpn_data_udp:/openvpn-udp
    ports:
      - "1194:1194/udp"
      - "5010:5010"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      EASY_RSA_PATH: "/openvpn-udp/easy-rsa"
      DATA_DIR: /openvpn-udp
      PORT: "1194"
      API_PORT: 5010
      PROTO: udp
      OpenVpnManagement__Port: "5092"
      OpenVpnManagement__Host: "localhost"
      BACKEND__BASEURL: "http://backend:5581/"
      WAN_IF: eth0
      VPN_SUBNET: "10.50.29.0"
      VPN_NETMASK: "255.255.255.0"

  openvpn_tcp:
    image: imkolganov/openvpn-gate-monitor-openvpn:latest
    pull_policy: always
    container_name: openvpn_tcp
    restart: unless-stopped
    networks:
      - backend_network
      - openvpn_network
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - openvpn_data_tcp:/openvpn-tcp
    ports:
      - "1195:1195"
      - "5011:5011"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      EASY_RSA_PATH: "/openvpn-tcp/easy-rsa"
      DATA_DIR: /openvpn-tcp
      PORT: "1195"
      API_PORT: 5011
      PROTO: tcp
      OpenVpnManagement__Port: "5093"
      OpenVpnManagement__Host: "localhost"
      BACKEND__BASEURL: "http://backend:5581/"
      WAN_IF: eth0
      VPN_SUBNET: "10.50.28.0"
      VPN_NETMASK: "255.255.255.0"

  postgres_backend:
    image: postgres:latest
    container_name: datagate_postgres_backend
    restart: always
    networks:
      - backend_network
      - openvpn_network
    volumes:
      - postgres_data_backend:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: datagate_backend
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: securepassword_backend

volumes:
  openvpn_data_tcp:
  openvpn_data_udp:
  postgres_data_backend:
  backend_data:

networks:
  openvpn_network:
    driver: bridge
  backend_network:
    driver: bridge
  tgbot_network:
    driver: bridge
