FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends openvpn iproute2 iptables ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /loadtests
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["python3"]
