services:
  pihole:
    image: pihole/pihole:latest
    container_name: datagate-pihole
    network_mode: "container:openvpn-tcp-wss"
    entrypoint: ["/bin/sh", "/scripts/wait-tun0-and-start.sh"]
    environment:
      TZ: ${TZ:-UTC}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      FTLCONF_dns_listeningMode: 'BIND'
      FTLCONF_dns_interface: ${PIHOLE_DNS_INTERFACE}
      FTLCONF_webserver_port: ${PIHOLE_WEB_PORT:-8080}
      FTLCONF_dns_blocking_active: 'false'
      FTLCONF_webserver_session_restore: 'false'
      FTLCONF_webserver_api_max_sessions: '32'
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
      - ./wait-tun0-and-start.sh:/scripts/wait-tun0-and-start.sh:ro
    restart: unless-stopped
